# Generated by Django 3.0.10 on 2020-10-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20201024_2246'),
        ('academy', '0001_initial'),
        ('users', '0002_academic_coordinator_doctor_emergencycontact_manager_person_personphone_profileimage_psychologist_si'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollment', models.CharField(max_length=10, unique=True)),
                ('place_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('has_children', models.BooleanField(blank=True, default=None, null=True)),
                ('number_of_children', models.IntegerField(blank=True, default=None, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('academic_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_information', to='academy.AcademicGroup')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='common.Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('final_score', models.FloatField(null=True)),
                ('comment', models.TextField(null=True)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('failure_metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.SubjectFailureMetric')),
                ('school_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SchoolCycle')),
                ('semester_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.PeriodNumber')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='students.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.SubjectType')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentSibling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sibling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Sibling')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentPhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Phone')),
                ('order', models.PositiveIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_phone', to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('common.phone',),
        ),
        migrations.CreateModel(
            name='StudentMedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Disability')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentMaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.MaritalStatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
                ('start_date', models.IntegerField(blank=True, null=True)),
                ('end_date', models.IntegerField(blank=True, null=True)),
                ('academic_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.AcademicDegree')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentIncome',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Income')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('common.income',),
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Address')),
                ('home_status_description', models.CharField(blank=True, max_length=255, null=True)),
                ('family_relationship', models.CharField(max_length=255)),
                ('members', models.IntegerField()),
                ('home_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.HomeStatus')),
                ('housing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.HousingType')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'verbose_name': 'Dirección de estudiantes',
                'verbose_name_plural': 'Direcciones de estudiantes',
                'default_permissions': (),
            },
            bases=('common.address',),
        ),
        migrations.CreateModel(
            name='HistoricalStudentMaritalStatus',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marital_status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.MaritalStatus')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.Student')),
            ],
            options={
                'verbose_name': 'historical student marital status',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudentAddress',
            fields=[
                ('address_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='common.Address')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('outdoor_number', models.CharField(max_length=50)),
                ('indoor_number', models.CharField(blank=True, max_length=50, null=True)),
                ('colony', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('home_status_description', models.CharField(blank=True, max_length=255, null=True)),
                ('family_relationship', models.CharField(max_length=255)),
                ('members', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('home_status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.HomeStatus')),
                ('housing_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.HousingType')),
                ('state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.State')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.Student')),
            ],
            options={
                'verbose_name': 'historical Dirección de estudiantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FamilyIncome',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Income')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
            bases=('common.income',),
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Person')),
                ('type', models.CharField(choices=[('father', 'Padre'), ('mother', 'Madre')], max_length=25)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('has_job', models.BooleanField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_job', models.CharField(blank=True, max_length=255, null=True)),
                ('profession_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_alive', models.BooleanField(blank=True, null=True)),
                ('academic_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.AcademicDegree')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parent', to='students.Student')),
            ],
            options={
                'verbose_name': 'Padre',
                'verbose_name_plural': 'Padres',
                'default_permissions': (),
                'unique_together': {('student', 'type')},
            },
            bases=('users.person',),
        ),
    ]
