# Generated by Django 3.0.10 on 2020-11-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='second_last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='second_name',
        ),
    ]
