# Generated by Django 3.0.10 on 2020-12-28 01:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20201129_1910'),
        ('students', '0003_auto_20201225_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_information',
        ),
        migrations.CreateModel(
            name='StudentAcademicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_information', to='academy.AcademicGroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_information', to='students.Student')),
            ],
            options={
                'verbose_name': 'Carrera de estudiante',
                'verbose_name_plural': 'Carreras de estudiante',
                'default_permissions': (),
            },
        ),
    ]
