# Generated by Django 3.0.10 on 2021-02-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201228_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinstitute',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentinstitute',
            name='start_date',
        ),
    ]
