# Generated by Django 3.0.10 on 2021-02-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210228_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinstitute',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinstitute',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
