# Generated by Django 3.0.10 on 2021-04-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210228_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmaritalstatus',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='studentmaritalstatus',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentphone',
            name='order',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentMaritalStatus',
        ),
        migrations.DeleteModel(
            name='StudentMaritalStatus',
        ),
    ]
