# Generated by Django 3.0.10 on 2021-04-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210402_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddress',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
