# Generated by Django 3.0.10 on 2021-05-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20210411_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentacademicinformation',
            unique_together={('student', 'is_active')},
        ),
    ]
