# Generated by Django 3.0.10 on 2021-05-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210510_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentincome',
            name='income_ptr',
        ),
        migrations.RemoveField(
            model_name='studentincome',
            name='student',
        ),
        migrations.DeleteModel(
            name='FamilyIncome',
        ),
        migrations.DeleteModel(
            name='StudentIncome',
        ),
    ]
