# Generated by Django 3.0.10 on 2021-05-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentincome',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.Student'),
            preserve_default=False,
        ),
    ]
