# Generated by Django 3.0.10 on 2021-05-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210510_0327'),
        ('students', '0012_studentincome_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparent',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Address'),
        ),
    ]
