# Generated by Django 3.0.10 on 2021-10-13 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20210613_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='semester_added',
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='studentincome',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='income', to='students.Student'),
        ),
    ]
