# Generated by Django 3.0.10 on 2021-11-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20210510_0327'),
        ('students', '0017_studentsubject_tutor_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubject',
            options={'default_permissions': (), 'verbose_name': 'Materia de estudiante', 'verbose_name_plural': 'Materias de estudiante'},
        ),
        migrations.AlterField(
            model_name='studentacademicinformation',
            name='academic_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.AcademicGroup'),
        ),
        migrations.AlterField(
            model_name='studentacademicinformation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='failure_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.SubjectFailureMetric'),
        ),
        migrations.CreateModel(
            name='StudentScholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_scholarship', models.BooleanField(default=False)),
                ('institute_name', models.BooleanField(blank=True, null=True)),
                ('dependence_name', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship', to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_job', models.BooleanField(default=False)),
                ('company_name', models.BooleanField(blank=True, null=True)),
                ('schedule', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
