# Generated by Django 3.0.10 on 2021-11-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20211107_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPsicofisiologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p2', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p3', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p4', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p5', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p6', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p7', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p8', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p9', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p10', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p11', models.CharField(choices=[('frecuente', 'frecuente'), ('muy frecuente', 'muy frecuente'), ('nunca', 'nunca'), ('antes', 'antes'), ('a veces', 'a veces')], max_length=20)),
                ('p12', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
