# Generated by Django 3.0.10 on 2021-11-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_estadopsicofisiologico'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopsicofisiologico',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estado_psicofisiologico', to='students.Student'),
            preserve_default=False,
        ),
    ]
