# Generated by Django 3.0.10 on 2021-11-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_estadopsicofisiologico_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopsicofisiologico',
            name='p8_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
