# Generated by Django 3.0.10 on 2021-11-19 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_estadopsicofisiologico_p8_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIntegracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p2', models.BooleanField()),
                ('p2_1', models.TextField(blank=True, null=True)),
                ('p3', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p4', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p5', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p6', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p7', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p8', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Hermano', 'Hermano'), ('Otros', 'Otros')], max_length=20)),
                ('p8_1', models.TextField(blank=True, null=True)),
                ('p9', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Hermano', 'Hermano'), ('Otros', 'Otros')], max_length=20)),
                ('p10', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p11', models.TextField(blank=True, null=True)),
                ('p12', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p13', models.TextField(blank=True, null=True)),
                ('p14', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p15', models.BooleanField()),
                ('p16', models.CharField(blank=True, choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20, null=True)),
                ('p17', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p18', models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20)),
                ('p19', models.TextField(blank=True, null=True)),
                ('p20', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='area_integracion', to='students.Student')),
            ],
        ),
    ]
