# Generated by Django 3.0.10 on 2021-11-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_areaintegracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaintegracion',
            name='p20',
        ),
        migrations.AddField(
            model_name='areaintegracion',
            name='p15_1',
            field=models.CharField(blank=True, choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p16',
            field=models.CharField(choices=[('buena', 'buena'), ('bien', 'bien'), ('regular', 'regular'), ('mala', 'mala'), ('mal', 'mal')], default='buena', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p18',
            field=models.TextField(),
        ),
    ]
