# Generated by Django 3.0.10 on 2021-11-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20211119_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaintegracion',
            name='p10',
            field=models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Hermano', 'Hermano'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
