# Generated by Django 3.0.10 on 2021-11-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20211119_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaintegracion',
            name='p1',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p12',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p14',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p15_1',
            field=models.CharField(blank=True, choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p16',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p17',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p3',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p4',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p5',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p6',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='areaintegracion',
            name='p7',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Bien', 'Bien'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Mal', 'Mal')], max_length=20),
        ),
    ]
