# Generated by Django 3.0.10 on 2021-11-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20211119_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p1',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p10',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p11',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p2',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p3',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p4',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p5',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p6',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p7',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p8',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopsicofisiologico',
            name='p9',
            field=models.CharField(choices=[('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente'), ('Nunca', 'Nunca'), ('Antes', 'Antes'), ('A veces', 'A veces')], max_length=20),
        ),
    ]
