# Generated by Django 3.0.10 on 2021-11-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_areapsicopedagogica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicaEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.BooleanField()),
                ('p2', models.BooleanField()),
                ('p3', models.BooleanField()),
                ('p4', models.BooleanField()),
                ('p5', models.BooleanField()),
                ('p6', models.BooleanField()),
                ('p7', models.BooleanField()),
                ('p8', models.BooleanField()),
                ('p9', models.BooleanField()),
                ('p10', models.BooleanField()),
                ('p11', models.BooleanField()),
                ('p12', models.BooleanField()),
                ('p13', models.BooleanField()),
                ('p14', models.BooleanField()),
                ('p15', models.BooleanField()),
                ('p16', models.BooleanField()),
                ('p17', models.BooleanField()),
                ('p18', models.BooleanField()),
                ('p19', models.BooleanField()),
                ('p20', models.BooleanField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tecnica_estudio', to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.BooleanField()),
                ('p2', models.BooleanField()),
                ('p3', models.BooleanField()),
                ('p4', models.BooleanField()),
                ('p5', models.BooleanField()),
                ('p6', models.BooleanField()),
                ('p7', models.BooleanField()),
                ('p8', models.BooleanField()),
                ('p9', models.BooleanField()),
                ('p10', models.BooleanField()),
                ('p11', models.BooleanField()),
                ('p12', models.BooleanField()),
                ('p13', models.BooleanField()),
                ('p14', models.BooleanField()),
                ('p15', models.BooleanField()),
                ('p16', models.BooleanField()),
                ('p17', models.BooleanField()),
                ('p18', models.BooleanField()),
                ('p19', models.BooleanField()),
                ('p20', models.BooleanField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organizacion_estudio', to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MotivacionEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.BooleanField()),
                ('p2', models.BooleanField()),
                ('p3', models.BooleanField()),
                ('p4', models.BooleanField()),
                ('p5', models.BooleanField()),
                ('p6', models.BooleanField()),
                ('p7', models.BooleanField()),
                ('p8', models.BooleanField()),
                ('p9', models.BooleanField()),
                ('p10', models.BooleanField()),
                ('p11', models.BooleanField()),
                ('p12', models.BooleanField()),
                ('p13', models.BooleanField()),
                ('p14', models.BooleanField()),
                ('p15', models.BooleanField()),
                ('p16', models.BooleanField()),
                ('p17', models.BooleanField()),
                ('p18', models.BooleanField()),
                ('p19', models.BooleanField()),
                ('p20', models.BooleanField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='motivacion_estudio', to='students.Student')),
            ],
        ),
    ]
