# Generated by Django 3.0.10 on 2021-11-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_motivacionestudio_organizacionestudio_tecnicaestudio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areapsicopedagogica',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='motivacionestudio',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='organizacionestudio',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='tecnicaestudio',
            options={'default_permissions': ()},
        ),
        migrations.CreateModel(
            name='EstiloAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p2', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p3', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p4', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p5', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p6', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p7', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p8', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p9', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p10', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p11', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p12', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p13', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p14', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p15', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p16', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p17', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p18', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p19', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p20', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p21', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p22', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p23', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('p24', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Usualmente'), (6, 'Siempre')])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estilo_aprendizaje', to='students.Student')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
