# Generated by Django 3.0.10 on 2021-11-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_auto_20211121_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p1',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p10',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p11',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p12',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p13',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p14',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p15',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p16',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p17',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p18',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p19',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p2',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p20',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p21',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p22',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p23',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p24',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p3',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p4',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p5',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p6',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p7',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p8',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
        migrations.AlterField(
            model_name='estiloaprendizaje',
            name='p9',
            field=models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Ocasionalmente'), (4, 'Usualmente'), (5, 'Siempre')]),
        ),
    ]
