# Generated by Django 3.0.10 on 2022-01-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_auto_20211125_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmedicalinformation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='studentsibling',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
