version: '3'


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tutorias_app
    container_name: django_pit
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - ${MEDIA_DATA}:${MEDIA_ROOT}
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tutorias_postgres
    container_name: postgres_pit
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data:Z
      - ${POSTGRES_BACKUPS}:/backups:z
    env_file:
      - .env
    ports:
      - "5434:5432"
