# Generated by Django 3.0.10 on 2020-10-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'academy_academic_major',
                'default_permissions': (),
                'default_related_name': 'academy_major',
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademicMajor')),
            ],
            options={
                'db_table': 'academy_academic_period',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriodNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademicPeriod')),
            ],
            options={
                'db_table': 'academy_academic_period_number',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'academy_group',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'academy_major',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Periodo academico',
                'verbose_name_plural': 'Periodos academicos',
                'db_table': 'academy_period',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PeriodNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Número de periodo',
                'verbose_name_plural': 'Número de periodos',
                'db_table': 'academy_period_number',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('first_value', models.IntegerField(default=0)),
                ('second_value', models.IntegerField(default=0)),
                ('total_value', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'academy_subject',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubjectFailureMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Métrica de reprobación',
                'verbose_name_plural': 'Métricas de reprobación',
                'db_table': 'academy_subject_failure_metric',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de materia',
                'verbose_name_plural': 'Tipos de materias',
                'db_table': 'academy_subject_type',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('careers', models.ManyToManyField(through='academy.AcademicMajor', to='academy.Major')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'academy_university',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('academic_period_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademicPeriodNumber')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Subject')),
            ],
            options={
                'db_table': 'academy_academic_subject',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='academicperiodnumber',
            name='period_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.PeriodNumber'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Period'),
        ),
        migrations.AddField(
            model_name='academicmajor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_major', to='academy.Major'),
        ),
        migrations.AddField(
            model_name='academicmajor',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_major', to='academy.University'),
        ),
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('academic_period_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademicPeriodNumber')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Group')),
            ],
            options={
                'db_table': 'academy_academic_group',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('academic_major', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='academicmajor',
            unique_together={('university', 'major')},
        ),
    ]
