# Generated by Django 3.0.10 on 2020-11-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicgroup',
            options={'default_permissions': (), 'verbose_name': 'Academia grupo', 'verbose_name_plural': 'Academia grupos'},
        ),
        migrations.AlterModelOptions(
            name='academicmajor',
            options={'default_permissions': (), 'default_related_name': 'academy_major', 'verbose_name': 'Carrera academia', 'verbose_name_plural': 'Carreras academia'},
        ),
        migrations.AlterModelOptions(
            name='academicperiod',
            options={'default_permissions': (), 'verbose_name': 'Periodo academia', 'verbose_name_plural': 'Periodos academia'},
        ),
        migrations.AlterModelOptions(
            name='academicperiodnumber',
            options={'default_permissions': (), 'verbose_name': 'Academia número de periodo', 'verbose_name_plural': 'Academia número de periodos'},
        ),
        migrations.AlterModelOptions(
            name='academicsubject',
            options={'default_permissions': (), 'verbose_name': 'Academia materia', 'verbose_name_plural': 'Academia materias'},
        ),
        migrations.RenameField(
            model_name='university',
            old_name='careers',
            new_name='majors',
        ),
    ]
