# Generated by Django 3.0.10 on 2020-10-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academicdegree',
            table='common_academic_degree',
        ),
        migrations.AlterModelTable(
            name='address',
            table='common_address',
        ),
        migrations.AlterModelTable(
            name='attitude',
            table='common_attitude',
        ),
        migrations.AlterModelTable(
            name='disability',
            table='common_disability',
        ),
        migrations.AlterModelTable(
            name='homestatus',
            table='common_home_status',
        ),
        migrations.AlterModelTable(
            name='housingtype',
            table='common_housing_type',
        ),
        migrations.AlterModelTable(
            name='income',
            table='common_income',
        ),
        migrations.AlterModelTable(
            name='maritalstatus',
            table='common_marital_status',
        ),
        migrations.AlterModelTable(
            name='relationship',
            table='common_relationship',
        ),
        migrations.AlterModelTable(
            name='schoolcycle',
            table='common_school_cycle',
        ),
    ]
