# Generated by Django 3.0.10 on 2021-05-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201024_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphone',
            name='type',
            field=models.CharField(choices=[('home_phone', 'Teléfono de Casa'), ('mobile_phone', 'Teléfono Celular')], max_length=15),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('home_phone', 'Teléfono de Casa'), ('mobile_phone', 'Teléfono Celular')], max_length=15),
        ),
    ]
