# Generated by Django 3.0.10 on 2021-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210510_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcycle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
