# Generated by Django 3.0.10 on 2021-05-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210417_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personphone',
            name='order',
        ),
        migrations.AlterField(
            model_name='personphone',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='users.Person'),
        ),
    ]
