# Generated by Django 3.0.10 on 2021-05-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210522_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personphone',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='users.Person'),
        ),
    ]
