# Generated by Django 3.0.10 on 2021-11-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211114_0418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseQuestionnaire',
        ),
    ]
