# Generated by Django 3.0.10 on 2021-11-14 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_coursequestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='courses.Course'),
            preserve_default=False,
        ),
    ]
