# Generated by Django 3.0.10 on 2021-11-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_stringanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stringanswer',
            old_name='string_response',
            new_name='response',
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_answer', to='courses.Question')),
            ],
            options={
                'verbose_name': 'Respuesta tipo texto',
                'verbose_name_plural': 'Respuestas tipo texto',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BoolAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_answer', to='courses.Question')),
            ],
            options={
                'verbose_name': 'Respuesta tipo bool',
                'verbose_name_plural': 'Respuestas tipo bool',
                'default_permissions': (),
            },
        ),
    ]
