# Generated by Django 3.0.10 on 2021-11-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211115_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
