# Generated by Django 3.0.10 on 2021-07-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20210510_0327'),
        ('tutor', '0002_auto_20210710_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorgroup',
            name='group_information',
        ),
        migrations.AddField(
            model_name='tutorgroup',
            name='academic_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_group', to='academy.AcademicGroup'),
            preserve_default=False,
        ),
    ]
