# Generated by Django 3.0.10 on 2021-07-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20210510_0327'),
        ('tutor', '0005_auto_20210718_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorsubject',
            name='academic_subject',
        ),
        migrations.AddField(
            model_name='tutorsubject',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.Subject'),
            preserve_default=False,
        ),
    ]
